sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
env:
  - ADDON="homebridge"
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - travis_wait 30 ./build.sh $ADDON
